### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by kinmic** [kinmic/Fish549-assignment_5#1]
Read in and plotted the data before conducting some filtering / cleaning.  From the cleaned dataset, I created a plot of the overall length distribution of the fish. I then used ggridges to created a ridgeline histogram plots of the distributions, coloured by sampling location. A distribution curve was then overlayed on top the the histograms. A colorblind friendly palette was selected from the color brewer package. Annotations matching the plots colors were added to label each site, in addition to the total number of fish collected from that site. A minimal theme was used on the plot to minimize visual clutter. The markdown was written to a pdf.

**Comment by mdscheuerell** [comment]
This is a really comprehensive submission, Mico. Well done! And I really like your the density plots overlaid on the histograms with the colored annotations as well.
